# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new  Build to Development"
  lane :build_development do
    gradle(task: "clean assembleDebug")
  
  end

  desc "Submit a build to Quality App Distribution with Crashlytics on"
  lane :build_quality do
    gradle(task: "clean assembleRelease")
    crashlytics

  end

end
