name: Android - Deployment Development - CI/CD w Fastlane

on:
  push:
    branches:
      - INT-220-config

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install Fastlane
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install
          bundle exec fastlane update_fastlane
          bundle exec fastlane install_plugins

      - name: Build APK with Fastlane
        run: |
          bundle exec fastlane build_development
