name: Android - Deployment Development

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Fetch signing json file
        run: | 
          echo $FIREBASE_CONFIG_JSON  >> "${{ github.workspace }}/In-telligent/app/signingConfig.json"
        env:
          GOOGLE_SIGNING_JSON: ${{ secrets.FIREBASE_CONFIG_JSON }}


      - name: Build APK with Gradle
        run: | 
          cd In-telligent
          chmod +x gradlew
          export SONAR_LOGIN=${{ secrets. SONAR_TOKEN }}
          ./gradlew assembleDebug
          ./gradlew sonar

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: In-telligent/build/sonar/report-task.txt
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 
      - name: "Show SonarQube Quality Gate Check Result"
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: ${{ github.workspace }}/In-telligent/app/build/outputs/apk/debug/*.apk
       
        
        
