name: Android - Deployment Quality

on:
  push:
    branches:
      - quality

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build APK with Gradle
        run: | 
          cd In-telligent
          chmod +x gradlew
          ./gradlew assembleDebug